# Generated by Django 5.1.2 on 2024-11-04 11:53

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rejected_at',
            field=model_utils.fields.MonitorField(default=None, monitor='state', when={'rejected'}),
        ),
        migrations.AlterField(
            model_name='service',
            name='started_at',
            field=model_utils.fields.MonitorField(default=None, monitor='state', when={'started'}),
        ),
    ]
