# Generated by Django 5.1.2 on 2024-11-04 12:00

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_service_rejected_at_alter_service_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rejected_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='state', null=True, when={'rejected'}),
        ),
        migrations.AlterField(
            model_name='service',
            name='started_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='state', null=True, when={'started'}),
        ),
    ]
