POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "maan", "password": "maan@admin" }
###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "alaa", "password": "alaa@admin", "fcm_token": "cocococo" }
###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "moutaz", "password": "moutaz@admin", "fcm_token": "wakwak"  }

###
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb

{"username": "moutaz"}
###

GET http://127.0.0.1:8000/department/2
Content-Type: application/json
Authorization: token c21e535cd341746ce33e4ca2343542d4a5e39621

{}
###
GET http://127.0.0.1:8000/department
Content-Type: application/json
Authorization: token c21e535cd341746ce33e4ca2343542d4a5e39621

{}

###
GET http://127.0.0.1:8000/employee/5
Content-Type: application/json
Authorization: token 66b4f94c3984997adfb0040f52ec6fe1ae83ca1a

{}

###
GET http://127.0.0.1:8000/service
Content-Type: application/json
Authorization: token 34378364ae39b0923229d6d64a8debc60e1810a0

{"id": 1 ,"message": "Echo Back", "hint": "Get me back"}

###
GET http://127.0.0.1:8000/service/1
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

{"message": "Echo Back", "hint": "Get me back"}


###
GET http://127.0.0.1:8000/stats
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

{}

###
GET http://127.0.0.1:8000/reports/device?
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

{}

###
GET http://127.0.0.1:8000/api/employee/2
Content-Type: application/json
# Authorization: token 66b4f94c3984997adfb0040f52ec6fe1ae83ca1a

{}

###

GET http://127.0.0.1:8000/api/service
Content-Type: application/json
# Authorization: token 66b4f94c3984997adfb0040f52ec6fe1ae83ca1a

{}

###

GET http://127.0.0.1:8000/api/feedback
Content-Type: application/json
Authorization: token 8901f2b85c2c86a58b2a02eb3d802edae4ac95ed

{}

###

GET http://127.0.0.1:8000/api/department/1
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb

{}

###

GET http://127.0.0.1:8000/get-employee-devices
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb

{"id":"5"}
###

GET http://127.0.0.1:8000/get-employee-services
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb

{"id":"5"}
###

POST http://127.0.0.1:8000/send-notification 
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"id":"5"} 
###

POST http://127.0.0.1:8000/add-service
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb0 

{
    "name": "test service",
    "client_id": "6",
    "description": "test service",
    "service_type_id": "1",
    "subtype_id": "10",
    "service_location_id": "2",
    "device_id": "3",
    }
###