### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "maan", "password": "maan@admin" }

### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "alaa", "password": "alaa@admin", "fcm_token": "alaa fcm_token" }

### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "ahmad", "password": "ahmad@admin", "fcm_token": "ahmad fcm_token" }

### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "moutaz", "password": "moutaz@admin", "fcm_token": "moutaz fcm_token"  }


### Logout
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: token 9839e453dfdae6095d9b0027bb191cc56e899fae

{"username": "alaa"}


### Get All Departments:
GET http://127.0.0.1:8000/department
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Department By ID:
GET http://127.0.0.1:8000/department/2
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get All Employees:
GET http://127.0.0.1:8000/employee
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Tech Employees:
GET http://127.0.0.1:8000/get-tech-employees
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Employee By ID:
GET http://127.0.0.1:8000/employee/8
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get All Services:
GET http://127.0.0.1:8000/service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Service By ID:
GET http://127.0.0.1:8000/service/44
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Employee Devices:
GET http://127.0.0.1:8000/get-employee-devices/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Employee Services:
GET http://127.0.0.1:8000/get-employee-services/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Test Notification:
POST http://127.0.0.1:8000/send-notification 
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"id":"5"} 


### Add Service
POST http://127.0.0.1:8000/add-service
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "Ahmad Laptop Test Feedback3","employee": 9,"description": "Feedback Test Service3","servie_type": 1,"subtype": 9,"servie_location": 1,"priority_level": 1, "device": 4}


### Edit Pending Service By Client: Required (id, name, description)
POST http://127.0.0.1:8000/edit-service-client
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"id": 46, "name": "Ahmad Laptop Test Feedback3 Edited","description": "Feedback Test Service3 Edited"}


### Manager Process Service: Required (id, name, description, worker, state) (reason if state is rejected)
POST http://127.0.0.1:8000/process-service-mgr
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 46, "name":"Ahmad Laptop Feedback3", "worker": 10, "state": "approved", "reason": ""}


### Tech view Services:
GET http://127.0.0.1:8000/view-service-tech/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech Process Service: Required (id, name, description, state) (diagnose,solution if state is ended)
POST http://127.0.0.1:8000/process-service-tech
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 46, "name":"Ahmad Laptop Test Feedback3", "state": "ended", "diagnose": "diag", "solution": "solution", "notes": "notes"}


### Client Add Feedback: Required (name, service, rate)
POST http://127.0.0.1:8000/add-feedback
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "feedback 46","service": 46,"rate": 4,"review": "Test Review for the test feedback"}


### Manager View Active Services
GET http://127.0.0.1:8000/active-service
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### Manager/SysAdmin View Pending Services
GET http://127.0.0.1:8000/pending-service
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### Manager View Archived Services
GET http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 


### Manager Archive Service
POST http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"id": 39, "state": "closed"}



################
##  ViewSets  ##
################

### GET All services With ViewSet
GET  http://127.0.0.1:8000/api/service/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 


### Add service With ViewSet
POST  http://127.0.0.1:8000/api/service/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"name": "test ADD service VIA ViewSet","employee": 6,"description": "test service18","servie_type": 2,"subtype": 8,"servie_location": 1,"priority_level": 4, "device": 1}


### Update service With ViewSet
PATCH  http://127.0.0.1:8000/api/service/26/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"name": "Teest service EDited With ViewSet", "state": "started"}


### GET One service By ID With ViewSet
GET  http://127.0.0.1:8000/api/service/26/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 


### Get Employee By ID:
GET http://127.0.0.1:8000/api/employee/8
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### Get Service By ID:
GET http://127.0.0.1:8000/api/service/1
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### Get All Feedbacks:
GET http://127.0.0.1:8000/api/feedback
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### Get Department By ID:
GET http://127.0.0.1:8000/api/department/1
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb



####################
### Stats & Reports
####################

### GET System Current Statistics:
GET http://127.0.0.1:8000/stats
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### GET Devices Reports
GET http://127.0.0.1:8000/reports/device?
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Feedbacks Reports
GET http://127.0.0.1:8000/reports/feedback
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Services Reports
GET http://127.0.0.1:8000/reports/service
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Service By Tech Reports
GET http://127.0.0.1:8000/reports/service-tech
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

