
### Get All Departments:
GET http://127.0.0.1:8000/department
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Department By ID:
GET http://127.0.0.1:8000/department/2
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get All Employees:
GET http://127.0.0.1:8000/employee
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Tech Employees:
GET http://127.0.0.1:8000/get-tech-employees
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee By ID:
GET http://127.0.0.1:8000/employee/10
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get All Services:
GET http://127.0.0.1:8000/service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Service By ID:
GET http://127.0.0.1:8000/service/47
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Devices:
GET http://127.0.0.1:8000/get-employee-devices/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Services:
GET http://127.0.0.1:8000/get-employee-services/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Add Service: Required (name, description, employee, servie_type, servie_location, priority_level) (device if it is needed) 
POST http://127.0.0.1:8000/add-service
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "Debug Service FCM","description": "Debug Service Description","employee": 9,"servie_type": 2,"subtype": 3,"servie_location": 3,"priority_level": 3, "device": 4}


### Edit Pending Service By Client: Required (id, name, description)
POST http://127.0.0.1:8000/edit-service-client
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"id": 51, "name": "Debug Service FCM Edited","description": "Debug Service Description Edited"}


### Manager Process Service: Required (id, name, description, worker, state) (reason if state is rejected)
POST http://127.0.0.1:8000/process-service-mgr
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 51, "name":"Debug Service Name Edited", "worker": 10, "state": "approved", "reason": ""}


### Tech View Approved Services:
GET http://127.0.0.1:8000/view-service-tech/approved/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech View Started Services:
GET http://127.0.0.1:8000/view-service-tech/started/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech Process Service: Required (id, name, description, state) (diagnose,solution if state is ended)
POST http://127.0.0.1:8000/process-service-tech
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 51, "state": "ended", "diagnose": "diag", "solution": "solution", "notes": "notes"}


### Client Add Feedback: Required (name, service, rate)
POST http://127.0.0.1:8000/add-feedback
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "feedback 51","service": 51,"rate": 4,"review": "Test Review for the test feedback"}


### Manager View All Feedbacks: Using ViewSets
GET http://127.0.0.1:8000/api/feedback
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Manager View Active Services
GET http://127.0.0.1:8000/active-service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Manager/SysAdmin View Pending Services
GET http://127.0.0.1:8000/pending-service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Manager View Archived Services
GET http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 

### Manager Archive Service: Required (id)
POST http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 

{"id": 51}


