
### Get All Departments:
GET http://127.0.0.1:8000/department
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Department By ID:
GET http://127.0.0.1:8000/department/2
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get All Employees:
GET http://127.0.0.1:8000/employee
Content-Type: application/json
Authorization: token 123246d394bc59fb48333f6e2d777f93e190cb71

### Get Tech Employees:
GET http://127.0.0.1:8000/get-tech-employees
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee By ID:
GET http://127.0.0.1:8000/employee/10
Content-Type: application/json
Authorization: token 123246d394bc59fb48333f6e2d777f93e190cb71

### Get All Services:
GET http://127.0.0.1:8000/service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Service By ID:
GET http://127.0.0.1:8000/service/47
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Devices:
GET http://127.0.0.1:8000/get-employee-devices/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Services:
GET http://127.0.0.1:8000/get-employee-services/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Add Service: Required (name, description, employee, servie_type, servie_location, priority_level) (device if it is needed) 
POST http://127.0.0.1:8000/add-service
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "No Name","description": "No Name Service test1","employee": 6,"servie_type": 3,"subtype": 8,"servie_location": 3,"priority_level": 4}


### Client Edit Pending/Rejected Service: Required (id, name, description) + in rejected All data to update the service
POST http://127.0.0.1:8000/edit-service-client
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"id": 55, "name": "Debug Service FCM Edited","description": "Debug Service Description Edited","priority_level": 1}


### Manager Process Service: Required (id, name, description)( worker, state if approved) (reason if state is rejected)
POST http://127.0.0.1:8000/process-service-mgr
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 55, "name":"Debug Service Name Edited", "worker": 10, "state": "approved", "reason": "Not Enough Info"}


### Tech View Approved Services:
GET http://127.0.0.1:8000/view-service-tech/approved/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech View Started Services:
GET http://127.0.0.1:8000/view-service-tech/started/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech Process Service: Required (id, name, description, state) (diagnose,solution if state is ended)
POST http://127.0.0.1:8000/process-service-tech
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 48, "state": "ended", "diagnose": "diag", "solution": "solution", "notes": "notes"}


### Client Add Feedback: Required (name, service, rate)
POST http://127.0.0.1:8000/add-feedback
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "feedback 51","service": 48,"rate": 3,"review": "Test Review for the test feedback"}


### Manager View All Feedbacks: Using ViewSets
GET http://127.0.0.1:8000/api/feedback
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Manager View Active Services
GET http://127.0.0.1:8000/active-service
Content-Type: application/json
Authorization: token 123246d394bc59fb48333f6e2d777f93e190cb71

### Manager/SysAdmin View Pending Services
GET http://127.0.0.1:8000/pending-service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Manager View Archived Services
GET http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token 123246d394bc59fb48333f6e2d777f93e190cb71 

### Manager Archive Service: Required (id)
POST http://127.0.0.1:8000/archive-service
Content-Type: application/json 
Authorization: token 123246d394bc59fb48333f6e2d777f93e190cb71 

{"id": 48}


### Check For APP Update: Required (current)
POST http://127.0.0.1:8000/update
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"current": "5.1"}