################################
##  Login And Authintication  ##
################################

### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "maan", "password": "maan@admin", "fcm_token": "maan fcm_token"}

### Login: Tech Login 
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "alaa", "password": "alaa@admin", "fcm_token": "alaa fcm_token"}

### Login: Tech Login 
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "george", "password": "george@admin", "fcm_token": "george fcm_token"}

### Login: Client Login 
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "ahmad", "password": "ahmad@admin", "fcm_token": "ahmad fcm_token"}

### Login: SysAdmin Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "moutaz", "password": "moutaz@admin", "fcm_token": "moutaz fcm_token"}


### Login: Manager Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "lina", "password": "lina@admin", "fcm_token": "lina fcm_token"}


### Logout
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: token 9839e453dfdae6095d9b0027bb191cc56e899fae

{"username": "alaa"}
