########################
###  Stats & Reports  ##
########################

### GET System Current Statistics:
GET http://127.0.0.1:8000/stats
Content-Type: application/json
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb


### GET Devices Reports
GET http://127.0.0.1:8000/reports/device?
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Feedbacks Reports
GET http://127.0.0.1:8000/reports/feedback
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Services Reports
GET http://127.0.0.1:8000/reports/service
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Service By Tech Reports
GET http://127.0.0.1:8000/reports/service-tech
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

