
################
##  ViewSets  ##
################

### GET All services With ViewSet
GET  http://127.0.0.1:8000/api/service/46
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 


### Add service With ViewSet
POST  http://127.0.0.1:8000/api/service/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"name": "test ADD service VIA ViewSet","employee": 6,"description": "test service18","servie_type": 2,"subtype": 8,"servie_location": 1,"priority_level": 4, "device": 1}


### Update service With ViewSet
PATCH  http://127.0.0.1:8000/api/service/26/
Content-Type: application/json 
Authorization: token ae27b42bcaa5bde3b247e8ee66b109cbc380b8cb 

{"name": "Teest service EDited With ViewSet", "state": "started"}


### GET One service By ID With ViewSet
GET  http://127.0.0.1:8000/api/service/26/
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Get Employee By ID:
GET http://127.0.0.1:8000/api/employee/10
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Service By ID:
GET http://127.0.0.1:8000/api/service/1
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get All Feedbacks:
GET http://127.0.0.1:8000/api/feedback
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Department By ID:
GET http://127.0.0.1:8000/api/department/1
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


