
### Get All Departments:
GET https://mcsproject.pythonanywhere.com/department
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Get Department By ID:
GET https://mcsproject.pythonanywhere.com/department/2
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get All Employees:
GET https://mcsproject.pythonanywhere.com/employee
Content-Type: application/json
Authorization: token f3f3c7edbbba322c8b31f6f5c5d481d98ebf648c

### Get Tech Employees:
GET https://mcsproject.pythonanywhere.com/get-tech-employees
Content-Type: application/json
Authorization: token f3f3c7edbbba322c8b31f6f5c5d481d98ebf648c

### Get Employee By ID:
GET https://mcsproject.pythonanywhere.com/employee/10
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get All Services:
GET https://mcsproject.pythonanywhere.com/service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Service By ID:
GET https://mcsproject.pythonanywhere.com/service/47
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Devices:
GET https://mcsproject.pythonanywhere.com/get-employee-devices/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Get Employee Services:
GET https://mcsproject.pythonanywhere.com/get-employee-services/9
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Add Service: Required (name, description, employee, servie_type, servie_location, priority_level) (device if it is needed) 
POST https://mcsproject.pythonanywhere.com/add-service
Content-Type: application/json 
Authorization: token f3f3c7edbbba322c8b31f6f5c5d481d98ebf648c 

{"name": "First Service Name3","description": "Test Service Description 1","employee": 5,"servie_type": 2,"subtype": 3,"servie_location": 3,"priority_level": 3, "device": 1}


### Edit Pending Service By Client: Required (id, name, description)
POST https://mcsproject.pythonanywhere.com/edit-service-client
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"id": 47, "name": "Debug Service Name Edited","description": "Debug Service Description Edited"}


### Manager Process Service: Required (id, name, description, worker, state) (reason if state is rejected)
POST https://mcsproject.pythonanywhere.com/process-service-mgr
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 47, "name":"Debug Service Name Edited", "worker": 10, "state": "approved", "reason": ""}


### Tech View Approved Services:
GET https://mcsproject.pythonanywhere.com/view-service-tech/approved/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech View Started Services:
GET https://mcsproject.pythonanywhere.com/view-service-tech/started/10
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 


### Tech Process Service: Required (id, name, description, state) (diagnose,solution if state is ended)
POST https://mcsproject.pythonanywhere.com/process-service-tech
Content-Type: application/json 
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b 

{"id": 46, "name":"Ahmad Laptop Test Feedback3", "state": "ended", "diagnose": "diag", "solution": "solution", "notes": "notes"}


### Client Add Feedback: Required (name, service, rate)
POST https://mcsproject.pythonanywhere.com/add-feedback
Content-Type: application/json 
Authorization: token a7921ac167bf57bbc1f6911293b1b54fbaf93f1d 

{"name": "feedback 46","service": 46,"rate": 4,"review": "Test Review for the test feedback"}


### Manager View All Feedbacks: Using ViewSets
GET https://mcsproject.pythonanywhere.com/api/feedback
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b


### Manager View Active Services
GET https://mcsproject.pythonanywhere.com/active-service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Manager/SysAdmin View Pending Services
GET https://mcsproject.pythonanywhere.com/pending-service
Content-Type: application/json
Authorization: token 92905dd20f35324056cdf4c5283e1ed014c7ce4b

### Manager View Archived Services
GET https://mcsproject.pythonanywhere.com/archive-service
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 

### Manager Archive Service: Required (id)
POST https://mcsproject.pythonanywhere.com/archive-service
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 

{"id": 46}


### Check For APP Update: Required (current)
POST https://mcsproject.pythonanywhere.com/update
Content-Type: application/json 
Authorization: token 69c3dc587573fd7a6e77cba81526eb51f84ae8ec 

{"current": "4.9"}


