########################
###  Stats & Reports  ##
########################

### GET System Current Statistics:
GET https://mcsproject.pythonanywhere.com/stats
Content-Type: application/json
Authorization: token f3f3c7edbbba322c8b31f6f5c5d481d98ebf648c


### GET Devices Reports
GET https://mcsproject.pythonanywhere.com/reports/device?
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Feedbacks Reports
GET https://mcsproject.pythonanywhere.com/reports/feedback
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Services Reports
GET https://mcsproject.pythonanywhere.com/reports/service
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61


### GET Service By Tech Reports
GET https://mcsproject.pythonanywhere.com/reports/service-tech
Content-Type: application/json
Authorization: token f72f4f9c55b84537c753239753679d7e77e7cf61

